# Powers the "♥ Sponsor" button at the top of this repository.
# Once your GitHub Sponsors profile is approved, add it by uncommenting:
# github: [subtiliorars]

ko_fi: subtiliorars
buy_me_a_coffee: subtilior.ars
custom: ["https://www.paypal.me/DanielRead413"]
